target-version = "py310"

extend-exclude = [
    "installer/lib/kconfiglib",
]

[lint]
# Start with high-confidence errors that are likely to represent broken code.
select = [
    "E9",
    "F63",
    "F7",
    "F82",
]
