# coding=UTF-8
#
# Happy Hare MMU Software
#
# A tiny tokenizer > parser > AST > writer pipeline for Klipper-style .cfg files.
# It reads a config buffer, builds an in-memory tree (sections, options, comments, whitespace, placeholders),
# lets you query/mutate it, then serializes back to text while preserving layout.
#
#  - Layout preservation: whitespace/comments are first-class nodes and retained through round trips
#  - Indented multi-line values: indentation signals continuation; a bare newline without leading space ends the value
#  - Full-line comments inside a multi-line value are transparent (like Klipper's configparser): the value
#    resumes on the next indented line. E.g. commenting out one of a [quad_gantry_level] "points:" lines
#  - Special-case gcode* options: parses their values literally to avoid misinterpreting gcode content
#  - Error recovery: an unparsable construct doesn't abort the parse. The offending text is kept verbatim in
#    an UnparsedNode (so round trips stay byte-exact), a marker comment is added and parsing resumes at the
#    next [section] or option. Callers can list the damage with ConfigBuilder.parse_errors()
#
# (\_/)
# ( *,*)
# (")_(") Happy Hare Ready
#
# This file may be distributed under the terms of the GNU GPLv3 license.
#

import sys
import os
import logging
import re
import copy

# Check for python 3.x
if sys.version_info[0] < 3:
    sys.stderr.write("ERROR: Python 3 is required to run Happy-Hare 4.x\n")
    sys.exit(1)

# Notes:
# {placeholder} style placeholders are no longer used with jinja templating
# {template} is used to support advanced multi-line config lists/dicts like:
#   drying_data: {
#       'pla':   (45, 300),
#       'hips':  (75, 600)
#   }
#
CONFIG_SPEC = [
    ("hidden_option_comment", re.compile(r"^[ \t]*# SUPPLEMENTAL / UNDOCUMENTED PARAMETERS[ \t]*(?=\r?\n|$)")),
    ("comment", re.compile(r"^[ \t]*[#;].*?(?=\{[^}]+\})")),
    ("comment", re.compile(r"^[ \t]*[#;].*")),
    ("whitespace", re.compile(r"^\s+")),
    # ("section", re.compile(r"^\[.+\]")),
    ("section", re.compile(r"^\[.+\](?=[ \t]*(?:[#;][^\r\n]*)?(?:\r?\n|$))")),  ("word", re.compile(r"^\w[\w%]*")),
    ("assign_op", re.compile(r"^[:=]")),
    ("placeholder", re.compile(r"^\{(?:PIN_|PARAM_)[^%}]+\}")),
    ("template", re.compile(r"^\{\%[\s\S]*?\%\}")),
    # ("template", re.compile(r"^\{\%[^\n]*\%\}")),
    ("template", re.compile(r"^\{\#[^\n]*\#\}")),
    ("template", re.compile(r"^\{\{[^\n]*\}\}")),
    ("unknown", re.compile(r"^\S")),
]
 
GCODE_BOUNDARY_OPTION   = re.compile(r"^variable_\w+[ \t]*[:=]")
MAGIC_EXCLUSION_COMMENT = re.compile(r"^# EXCLUDE FROM CONFIG BUILDER.*")

# Klipper's own SAVE_CONFIG block: everything from this marker to EOF is auto-generated by
# Klipper and must never be touched. Nothing may be inserted at or after it
SAVE_CONFIG_MARKER      = re.compile(r"^#\*#\s*<-+\s*SAVE_CONFIG\s*-+>")

# A whole line that is nothing but a comment, and a line that continues a multi-line value
COMMENT_ONLY_LINE       = re.compile(r"^[ \t]*[#;]")
CONTINUATION_LINE       = re.compile(r"^[ \t]+\S")

# Where parsing can safely pick up again after an error: a new [section] or a new option
RESYNC_LINE             = re.compile(r"^(?:\[[^\r\n]*\]|\w[\w%]*[ \t]*[:=])")

# Marker comment left in the config to show where parsing failed. Must be recognizable so a
# re-run replaces it rather than stacking up another copy
PARSE_ERROR_MARKER      = "# !! HAPPY HARE PARSE ERROR"
MAX_RECOVERIES          = 50

if sys.version_info[0] >= 3:
    unicode = str


class ConfigSyntaxError(SyntaxError):
    """
    SyntaxError that also carries the bits needed to report/recover: a short one-line
    reason (no context block) plus the location it happened at.
    """

    def __init__(self, reason, line=None, col=None, origin=None, context=""):
        SyntaxError.__init__(self, "{} \n{}".format(reason, context))
        self.reason = reason
        self.line = line
        self.col = col
        self.origin = origin
        self.context = context


class Token(object):
    def __init__(self, type, value, line=None, col=None, pos=None, origin=None):
        self.type = type
        self.value = value
        self.line = line
        self.col = col
        self.pos = pos
        self.origin = origin

    def __repr__(self):
        return "{}: {}".format(self.type, self.value)


class Tokenizer(object):
    def __init__(self, buf, spec, origin=None):
        self.buf = buf
        self.slice = buf[:]
        self.next_token = None
        self.spec = spec
        self.origin = origin

        self.pos = 0
        self.line = 1
        self.col = 1

    def __iter__(self):
        return self

    def next(self):
        return self.__next__()

    def _recompute_line_col(self):
        if self.pos <= 0:
            self.line = 1
            self.col = 1
            return
        self.line = self.buf.count("\n", 0, self.pos) + 1
        last_nl = self.buf.rfind("\n", 0, self.pos)
        if last_nl == -1:
            self.col = self.pos + 1
        else:
            self.col = self.pos - last_nl

    def _format_error_context(self, line=None, col=None, origin=None, window=2):
        origin = origin if origin is not None else self.origin
        line = line if line is not None else self.line
        col = col if col is not None else self.col

        lines = self.buf.splitlines(True)  # keepends
        if not lines:
            loc = ""
            if origin:
                loc += "{}:".format(origin)
            loc += "{}:{}".format(line, col)
            return "  at {}\n".format(loc)

        idx = max(0, min(len(lines) - 1, line - 1))
        start = max(0, idx - window)
        end = min(len(lines), idx + window + 1)

        context = []
        for i in range(start, end):
            prefix = ">" if i == idx else " "
            txt = lines[i].rstrip("\n").rstrip("\r")
            context.append("{} {:4d} | {}".format(prefix, i + 1, txt))

        caret_pad = len("{} {:4d} | ".format(">", idx + 1))
        pointer = " " * (caret_pad + max(0, col - 1)) + "^"

        loc = ""
        if origin:
            loc += "{}:".format(origin)
        loc += "{}:{}".format(line, col)

        return "  at {}\n\n{}\n{}".format(loc, "\n".join(context), pointer)

    def __next__(self):
        if self.next_token is not None:
            next_token = self.next_token
            self.next_token = None
            return next_token

        if len(self.slice) == 0:
            raise StopIteration

        start_line = self.line
        start_col = self.col
        start_pos = self.pos

        for token_type, regex in self.spec:
            match = regex.match(self.slice)
            if match:
                value = match.group(0)

                # Advance absolute position counters
                self.pos += len(value)
                self._recompute_line_col()

                self.slice = self.slice[match.end() :]
                return Token(token_type, value, start_line, start_col, start_pos, self.origin)

        # Unknown/unmatchable byte (should be rare since 'unknown' exists, but keep defensive)
        ch = self.slice[0]
        raise ConfigSyntaxError(
            "Unexpected token '{}'".format(ch),
            start_line,
            start_col,
            self.origin,
            self._format_error_context(start_line, start_col, self.origin),
        )

    def peek(self):
        if self.next_token is None:
            try:
                self.next_token = next(self)
            except StopIteration:
                return None
        return self.next_token

    def take(self, token_type):
        try:
            token = next(self)
        except StopIteration:
            token = None  # end of file - report it like any other mismatch
        if token and token.type == token_type:
            return token
        else:
            got = token.type if token else "end of file"
            line = token.line if token else self.line
            col = token.col if token else self.col
            raise ConfigSyntaxError(
                "Expected {}, got {}".format(token_type, got),
                line,
                col,
                self.origin,
                self._format_error_context(line, col, self.origin),
            )

    def unread(self, s):
        if s:
            self.next_token = None
            self.slice = s + self.slice
            self.pos -= len(s)
            if self.pos < 0:
                self.pos = 0
            self._recompute_line_col()

    def consume(self, token_type):
        peek = self.peek()
        if peek and peek.type == token_type:
            self.take(token_type)

    def resync(self, start_pos, to_eof=False):
        """
        Error recovery. Rewind to `start_pos` (the start of the construct that failed) and
        swallow raw text up to the beginning of the next line that can start a fresh
        construct - a [section] header or an option assignment. The skipped text is
        returned so it can be preserved verbatim.

        At least the remainder of the failing line is always consumed, so the caller is
        guaranteed to make progress and cannot loop.
        """
        start_pos = max(0, min(start_pos, len(self.buf)))

        nl = self.buf.find("\n", start_pos)
        pos = len(self.buf) if nl == -1 else nl + 1
        while pos < len(self.buf) and not to_eof:
            nl = self.buf.find("\n", pos)
            line = self.buf[pos:] if nl == -1 else self.buf[pos:nl]
            if RESYNC_LINE.match(line):
                break
            pos = len(self.buf) if nl == -1 else nl + 1
        if to_eof:
            pos = len(self.buf)

        text = self.buf[start_pos:pos]
        self.next_token = None
        self.pos = pos
        self.slice = self.buf[pos:]
        self._recompute_line_col()
        return text


class Node(object):
    def __init__(self, type):
        self.type = type

    def _pretty_print(self, tab=4):
        def _print(node, lines, depth):
            lines.append(" " * depth * tab + type(node).__name__)
            for k, v in vars(node).items():
                if k in ["type", "body"]:
                    continue
                lines.append(unicode(" " * (depth + 1) * tab + "{}: `{}`").format(k, v))
            return True, lines

        lines = self.walk(_print, []) or []
        return unicode("\n".join(lines))

    def __str__(self):
        return self._pretty_print()

    def walk(self, callback, context=None, depth=0):
        _, context = callback(self, context, depth)
        return context

    def serialize(self):
        return unicode("")


class BodyNode(Node):
    def __init__(self, type, body):
        super(BodyNode, self).__init__(type)
        self.body = body

    def walk(self, callback, context=None, depth=0):
        cont, context = callback(self, context, depth)
        if cont:
            for item in self.body:
                context = item.walk(callback, context, depth + 1)
        return context


class DocumentNode(BodyNode):
    def __init__(self, body=None):
        super(DocumentNode, self).__init__("document", body or [])


class MagicExclusionNode(BodyNode):
    def __init__(self, body, origin=None):
        # All nodes after the magic comment live here
        BodyNode.__init__(self, "magic_exclusion", body)
        self.origin = origin


def _is_magic_comment_token(peek):
    return peek is not None and peek.type == "comment" and MAGIC_EXCLUSION_COMMENT.match(peek.value.lstrip())


class HiddenOptionCommentNode(Node):
    def __init__(self, value):
        Node.__init__(self, "hidden_option_comment")
        self.value = value

    def serialize(self):
        return self.value


class SectionNode(BodyNode):
    def __init__(self, name, body):
        BodyNode.__init__(self, "section", body)
        self.name = name

    def serialize(self):
        return unicode("[" + self.name + "]")


class OptionNode(BodyNode):
    def __init__(self, name, value, assign_op, trailing_ws=""):
        BodyNode.__init__(self, "option", value)
        self.name = name
        self.assign_op = assign_op
        self.trailing_ws = trailing_ws

    def serialize(self):
        return self.name + self.trailing_ws + self.assign_op

    def value(self, default=None, with_comments=False):
        if len(self.body) == 0:
            return default

        def serialize(node, buf, _):
            if not with_comments and isinstance(node, CommentNode):
                return False, buf
            return True, buf + node.serialize()

        value = ""
        for value_line in self.body:
            value = value_line.walk(serialize, value)
        return value.strip()


class ValueLineNode(BodyNode):
    def __init__(self, body):
        BodyNode.__init__(self, "value_line", body)


class ValueEntryNode(Node):
    def __init__(self, value):
        Node.__init__(self, "value_entry")
        self.value = value

    def serialize(self):
        return self.value


class CommentNode(BodyNode):
    def __init__(self, body):
        BodyNode.__init__(self, "comment", body)


class CommentEntryNode(Node):
    def __init__(self, value):
        Node.__init__(self, "comment_entry")
        self.value = value

    def serialize(self):
        return self.value


class PlaceholderNode(Node):
    def __init__(self, value):
        Node.__init__(self, "placeholder")
        self.value = value

    def serialize(self):
        return "{" + self.value + "}"


class WhitespaceNode(Node):
    def __init__(self, value):
        Node.__init__(self, "whitespace")
        self.value = value

    def serialize(self):
        return self.value


class UnparsedNode(Node):
    """
    Text the parser could not make sense of. Kept exactly as it was read so writing the
    document back out never loses or mangles a user's config, and tagged with why/where so
    the installer can tell them about it.
    """

    def __init__(self, value, line=None, origin=None, reason=None):
        Node.__init__(self, "unparsed")
        self.value = value
        self.line = line
        self.origin = origin
        self.reason = reason

    def serialize(self):
        return self.value


class TemplateNode(Node):
    def __init__(self, value):
        Node.__init__(self, "template")
        self.value = value

    def serialize(self):
        return self.value


class Parser(object):
    def __init__(self, default_assign_op=":", default_comment_ch="#", recover=True, error_marker=True):
        self.origin = None
        self.default_assign_op = default_assign_op
        self.default_comment_ch = default_comment_ch
        self.recover = recover              # keep going after a syntax error instead of raising
        self.error_marker = error_marker    # leave a marker comment in the config at the bad spot
        self.recoveries = 0

    def _syntax_error(self, tokenizer, message, peek=None, include_token=True):
        if peek is not None and getattr(peek, "line", None) is not None:
            line = peek.line
            col = peek.col
        else:
            line = getattr(tokenizer, "line", None)
            col = getattr(tokenizer, "col", None)

        origin = self.origin or getattr(tokenizer, "origin", None)

        token_info = " '{}'".format(peek) if peek is not None and include_token else ""
        ctx = tokenizer._format_error_context(line, col, origin) if hasattr(tokenizer, "_format_error_context") else ""
        raise ConfigSyntaxError("{}{}".format(message, token_info), line, col, origin, ctx)

    def parse(self, buffer, origin=None):
        self.origin = origin
        self.recoveries = 0
        tokenizer = Tokenizer(buffer, CONFIG_SPEC, origin=origin)
        return self._post_process(self.parse_document(tokenizer))

    def _recover(self, tokenizer, err, start_pos):
        """
        Turn a syntax error into a reported-but-survivable one. Everything from the start of
        the failing construct up to the next section/option is kept verbatim in an
        UnparsedNode, followed by a marker comment so the user can find it in the file.

        The marker goes *after* the skipped text, on a line of its own: a comment there is
        always legal to Klipper, whereas inserting one ahead of a partially consumed line
        would rewrite the meaning of that line.
        """
        self.recoveries += 1
        if not self.recover:
            raise err

        # A config this broken isn't worth chasing line by line - keep the rest verbatim
        give_up = self.recoveries > MAX_RECOVERIES
        text = tokenizer.resync(start_pos, to_eof=give_up)
        if give_up:
            logging.error("Too many parse errors - the remainder of the file was left unparsed")

        # Drop markers left by an earlier run so repeated builds don't stack them up
        without_markers = "\n".join([l for l in text.split("\n") if not l.lstrip().startswith(PARSE_ERROR_MARKER)])
        text = without_markers if without_markers.strip() else text
        if not text:
            return []

        reason = getattr(err, "reason", None) or unicode(err).splitlines()[0].strip()
        line = getattr(err, "line", None)
        origin = self.origin or getattr(tokenizer, "origin", None)

        logging.error("Unable to parse {}{}".format("{} ".format(origin) if origin else "", unicode(err)))
        logging.error(
            "Skipped {} unparsable line(s) from line {} and carried on".format(
                len(text.strip("\n").split("\n")), line
            )
        )

        nodes = [UnparsedNode(text, line=line, origin=origin, reason=reason)]
        if self.error_marker:
            if not text.endswith("\n"):
                nodes.append(WhitespaceNode("\n"))
            # Deliberately no line number in the marker: it has to survive a rebuild that
            # inserts an [include] above it without the text changing, or every install
            # would churn the user's config
            marker = "{}: {} - line(s) above left untouched, please fix".format(PARSE_ERROR_MARKER, reason)
            nodes.append(CommentNode([CommentEntryNode(marker)]))
            nodes.append(WhitespaceNode("\n"))
        return nodes

    def filter_tree(self, node, predicate):
        """
        Remove any node (and its subtree) for which predicate(node) is True.
        Operates in-place.
        """

        def _filter_tree(parent, cur):
            # If this node should be removed, prune it from the parent and stop descending.
            if predicate(cur):
                if isinstance(parent, BodyNode):
                    try:
                        parent.body.remove(cur)
                    except ValueError:
                        pass  # already removed or not present
                return

            # Otherwise descend into children if present.
            if isinstance(cur, BodyNode):
                for child in list(cur.body):  # iterate over a snapshot to avoid skipping
                    _filter_tree(cur, child)

        _filter_tree(None, node)

    def parse_document(self, tokenizer):
        def _parse_regular(peek, body):
            start_pos = peek.pos
            try:
                if peek.type == "section":
                    body.append(self.parse_section(tokenizer))
                elif peek.type == "hidden_option_comment":
                    body.append(self.parse_hidden_option_comment(tokenizer))
                elif peek.type == "comment":
                    body.append(self.parse_comment(tokenizer))
                elif peek.type == "whitespace":
                    body.append(self.parse_whitespace(tokenizer))
                elif peek.type == "placeholder":
                    body.append(self.parse_placeholder(tokenizer))
                elif peek.type == "template":
                    body.append(self.parse_template(tokenizer))
                else:
                    self._syntax_error(tokenizer, "Expected a [section], an option or a comment, got", peek)
            except SyntaxError as err:
                body.extend(self._recover(tokenizer, err, start_pos))

        body = []
        peek = tokenizer.peek()

        while peek:
            # Start exclusion block: the magic comment and then everything to EOF
            if _is_magic_comment_token(peek):
                magic_comment = self.parse_comment(tokenizer)  # Keep the marker as a real comment
                exclusion_body = [magic_comment]

                peek2 = tokenizer.peek()
                while peek2:
                    _parse_regular(peek2, exclusion_body)
                    peek2 = tokenizer.peek()

                body.append(MagicExclusionNode(exclusion_body, self.origin))
                break  # Everything else is now inside the exclusion node

            _parse_regular(peek, body)
            peek = tokenizer.peek()

        return DocumentNode(body)

    def _post_process(self, document):
        """Move trailing whitespace/comments from sections a level up to be part of the document body"""
        new_body = []
        for item in document.body:
            new_body.append(item)
            if isinstance(item, SectionNode):
                # Find the index of the next item after last option in the section
                idx = max([i + 1 for i, n in enumerate(item.body) if isinstance(n, OptionNode)] or [0])
                if len(item.body) <= idx:
                    continue
                # If the next item is whitespace, still keep it in the section
                if isinstance(item.body[idx], WhitespaceNode):
                    idx += 1
                # All remaining items get moved up a level
                if len(item.body) > idx:
                    new_body += item.body[idx:]
                    item.body = item.body[:idx]

        document.body = new_body
        return document

    def parse_section(self, tokenizer):
        token = tokenizer.take("section")
        body = []

        peek = tokenizer.peek()
        while peek and peek.type != "section":
            if _is_magic_comment_token(peek):
                break  # Do not consume here—let parse_document() handle it

            start_pos = peek.pos
            try:
                if peek.type == "hidden_option_comment":
                    body.append(self.parse_hidden_option_comment(tokenizer))
                elif peek.type == "comment":
                    body.append(self.parse_comment(tokenizer))
                elif peek.type == "word":
                    body.append(self.parse_option(tokenizer))
                elif peek.type == "placeholder":
                    body.append(self.parse_placeholder(tokenizer))
                elif peek.type == "whitespace":
                    body.append(self.parse_whitespace(tokenizer))
                elif peek.type == "template":
                    body.append(self.parse_template(tokenizer))
                else:
                    self._syntax_error(tokenizer, "Expected a [section], an option or a comment, got", peek)
            except SyntaxError as err:
                body.extend(self._recover(tokenizer, err, start_pos))
            peek = tokenizer.peek()

        return SectionNode(token.value[1:-1], body)

    def parse_option(self, tokenizer):
        token = tokenizer.take("word")
        trailing_ws = ""
        peek = tokenizer.peek()
        if peek is None:
            self._syntax_error(tokenizer, "Unexpected end of file after '{}'".format(token.value))
        if peek.type == "whitespace":
            trailing_ws = tokenizer.take("whitespace").value

        # Spelled out rather than left as a bare "Expected assign_op": this is the error a
        # user actually hits (e.g. an orphaned value line) and they have to act on it. Kept
        # short because it also ends up in the marker comment written into their config
        peek = tokenizer.peek()
        if peek is None or peek.type != "assign_op":
            self._syntax_error(
                tokenizer, "Expected ':' or '=' after '{}'".format(token.value), peek, include_token=False
            )
        assign_op = tokenizer.take("assign_op").value
        if token.value.startswith("gcode"):  # parse gcode options as-is, so we don't parse gcode as structure'
            value = self.parse_value(tokenizer, as_is=True)
        else:
            value = self.parse_value(tokenizer)

        return OptionNode(token.value, value, assign_op, trailing_ws)

    def _continues_after_comments(self, tokenizer, token):
        """
        Called where a multi-line value would normally end (a newline with nothing indented
        after it). Klipper's configparser treats a whole-line comment as invisible inside a
        value, so a value can be interrupted by commented out lines and still continue. E.g.

            points:
            ### 30, 5
                50, 10
                150, 225

        Peek past a run of comment-only lines and report whether an indented continuation
        line follows. Blank lines still end a value, as they always have here.
        """
        if token.value.count("\n") != 1:
            return False

        rest = tokenizer.slice  # text after the peeked newline, so starts at column 1 of a line
        pos = 0
        while pos < len(rest):
            eol = rest.find("\n", pos)
            line = rest[pos:] if eol == -1 else rest[pos:eol]
            if not COMMENT_ONLY_LINE.match(line):
                return CONTINUATION_LINE.match(line) is not None
            if eol == -1:
                return False
            pos = eol + 1
        return False

    def parse_value(self, tokenizer, as_is=False):
        body = []
        current_entry = ""
        current_line = []

        brace_depth = 0
        bracket_depth = 0
        paren_depth = 0
        in_sq = False
        in_dq = False
        esc = False

        # Helper to balance bracketing in multi-line config options
        def _scan_balance(s):
            nonlocal brace_depth, bracket_depth, paren_depth, in_sq, in_dq, esc
            for ch in s:
                if esc:
                    esc = False
                    continue
                if ch == "\\":
                    esc = True
                    continue
                if in_sq:
                    if ch == "'":
                        in_sq = False
                    continue
                if in_dq:
                    if ch == '"':
                        in_dq = False
                    continue
                if ch == "'":
                    in_sq = True
                elif ch == '"':
                    in_dq = True
                elif ch == "{":
                    brace_depth += 1
                elif ch == "}":
                    brace_depth = max(0, brace_depth - 1)
                elif ch == "[":
                    bracket_depth += 1
                elif ch == "]":
                    bracket_depth = max(0, bracket_depth - 1)
                elif ch == "(":
                    paren_depth += 1
                elif ch == ")":
                    paren_depth = max(0, paren_depth - 1)

        def _looks_like_gcode_boundary(s):
            first_line = s.lstrip(" \t\r\n").splitlines()[0] if s.strip() else ""
            return (
                first_line.startswith("[")
                or GCODE_BOUNDARY_OPTION.match(first_line) is not None
            )

        peek = tokenizer.peek()
        while peek:
            if peek.type == "whitespace":
                if peek.value.startswith("\n") and peek.value.endswith("\n"):
                    # Original rule: end multi-line value when newline isn't followed by indent.
                    # Extension: if we're inside a bracketed structure, keep going so we can see the closing brace.
                    if (brace_depth == 0 and bracket_depth == 0 and paren_depth == 0 and not in_sq and not in_dq):
                        # gcode block exception
                        if as_is:
                            next_text = tokenizer.slice.lstrip(" \t\r\n")

                            if _looks_like_gcode_boundary(next_text):
                                break

                            # Otherwise keep consuming gcode lines.
                            pass
                        elif not self._continues_after_comments(tokenizer, token=peek):
                            break
                        # else: only full-line comments separate us from more indented value
                    # else: we're inside {...}/(...)/[...] so don't break

                token = tokenizer.take("whitespace")
 
                # Ensure whitespace for empty options is tokenized in ValueLineNode (only newline is standalone)
                m = re.search(r"\r?\n", token.value)
                if m and m.start() > 0:
                    tokenizer.unread(token.value[m.start() :])
                    token.value = token.value[: m.start()]
 
                if len(body) == 0 and len(current_line) == 0 and len(current_entry) == 0:
                    current_line.append(WhitespaceNode(token.value))
                else:
                    current_entry += token.value
                    _scan_balance(token.value)
 
                idx = current_entry.find("\n")
                while idx != -1:
                    current_line.append(ValueEntryNode(current_entry[: idx + 1]))
                    current_entry = current_entry[idx + 1 :]
                    body.append(ValueLineNode(current_line))
                    current_line = []
                    idx = current_entry.find("\n")
 
            elif not as_is and peek.type == "comment":
                if len(current_entry) > 0:
                    current_line.append(ValueEntryNode(current_entry))
                    current_entry = ""
                current_line.append(self.parse_comment(tokenizer))

            # Escape hatch, so that a [section] token doesn't fall into the generic
            # else and get swallowed into the gcode value
            elif as_is and peek.type == "section":
                break

            # A comment's text is prose, not code: quotes/brackets inside it (e.g. a
            # contraction like "don't") must never affect the brace/bracket/paren/quote
            # balance used above to detect the end of the gcode value, or the value
            # swallows everything up to the next [section] - silently absorbing any
            # variable_* options that follow the gcode: line in the same section.
            elif as_is and peek.type == "comment":
                current_entry += next(tokenizer).value

            elif not as_is and peek.type == "placeholder":
                if len(current_entry) > 0:
                    current_line.append(ValueEntryNode(current_entry))
                    current_entry = ""
                current_line.append(self.parse_placeholder(tokenizer))
 
            elif peek.type == "template":
                t = tokenizer.take("template").value
                current_entry += t
                _scan_balance(t)
 
            else:
                v = next(tokenizer).value
                current_entry += v
                _scan_balance(v)
 
            peek = tokenizer.peek()
 
        if len(current_entry) > 0:
            current_line.append(ValueEntryNode(current_entry))
 
        if len(current_line) > 0:
            body.append(ValueLineNode(current_line))
 
        return body

    def parse_comment(self, tokenizer):
        token = tokenizer.take("comment")
        current_comment = token.value
        body = []

        peek = tokenizer.peek()
        while peek:
            if peek.type == "whitespace":
                if peek.value.find("\n") != -1:
                    break
                current_comment += tokenizer.take("whitespace").value
            elif peek.type == "placeholder":
                if len(current_comment) > 0:
                    body.append(CommentEntryNode(current_comment))
                    current_comment = ""
                body.append(self.parse_placeholder(tokenizer))
            else:
                current_comment += next(tokenizer).value

            peek = tokenizer.peek()

        if len(current_comment) > 0:
            body.append(CommentEntryNode(current_comment))

        return CommentNode(body)

    def parse_hidden_option_comment(self, tokenizer):
        token = tokenizer.take("hidden_option_comment")
        return HiddenOptionCommentNode(token.value)

    def parse_placeholder(self, tokenizer):
        placeholder = tokenizer.take("placeholder")
        return PlaceholderNode(placeholder.value[1:-1])

    def parse_whitespace(self, tokenizer):
        token = tokenizer.take("whitespace")
        return WhitespaceNode(token.value)

    def parse_template(self, tokenizer):
        token = tokenizer.take("template")
        return TemplateNode(token.value)


def collect(node, ctx):
    ctx.append(node)
    return ctx


def identity(node, _):
    return node


def rename(node, ctx):
    node.name = ctx
    return ctx


class ConfigBuilder(object):
    def __init__(self, filename=None, parser=Parser()):
        self.filename = filename
        self.parser = parser
        self.document = DocumentNode()
        if self.filename:
            with open(self.filename, "r") as f:
                # Pass the name so any parse error can say which file it was in
                self.document = self.parser.parse(f.read(), os.path.basename(self.filename))

    def read(self, filename, origin=None):
        with open(filename, "r") as f:
            doc = self.parser.parse(f.read(), origin)
            self.document.body += doc.body

    def read_buf(self, buf):
        doc = self.parser.parse(buf)
        self.document.body += doc.body

    def read_test(self, b):
        self.document.body = b

    # Dumps a tree view to stdout for debugging
    def pretty_print_document(self):
        def print_node(node, ctx, _):
            logging.debug(node._pretty_print())
            return True, ctx

        print(self.document._pretty_print())

    def write(self):
        def print_node(node, buffer, _):
            buffer += node.serialize()
            return True, buffer

        return self.document.walk(print_node, "")

    def parse_errors(self):
        """
        Return the UnparsedNode for every region that failed to parse, across all files
        read/merged into this document. Empty list means the config was fully understood.
        """

        def collect_unparsed(node, acc, _depth):
            if isinstance(node, UnparsedNode):
                acc.append(node)
            return True, acc

        return self.document.walk(collect_unparsed, [])

    def excluded_nodes(self, origin=None):
        """
        Return a list of all MagicExclusionNode instances in the current document,
        across all files that have been read/merged.
        """

        def collect_magic(node, acc, _depth):
            if isinstance(node, MagicExclusionNode) and (origin is None or node.origin == origin):
                acc.append(node)
            return True, acc  # Keep descending

        return self.document.walk(collect_magic, [])

    def delete_excluded(self, origin=None):
        """
        Remove every MagicExclusionNode (and all of its children) from the document.
        Returns the number of nodes removed.
        """
        to_remove = len(self.excluded_nodes(origin=origin))
        if to_remove == 0:
            return 0
        # Filter_tree prunes matching nodes and their entire subtree in-place
        self.parser.filter_tree(
            self.document, lambda n: isinstance(n, MagicExclusionNode) and (origin is None or n.origin == origin)
        )
        return to_remove

    def _iter_section_nodes(self, node, inside_excluded=False):
        """
        Yield (SectionNode, is_excluded) pairs from the tree rooted at `node`.
        Exclusion only flips to True when descending into a MagicExclusionNode.
        """
        if isinstance(node, SectionNode):
            yield node, inside_excluded
            return

        if isinstance(node, MagicExclusionNode):
            for child in node.body:
                # Descend with inside_excluded=True
                for pair in self._iter_section_nodes(child, True):
                    yield pair
            return

        if isinstance(node, DocumentNode):
            for child in node.body:
                # Reset inside_excluded at each top-level sibling (critical!)
                for pair in self._iter_section_nodes(child, False):
                    yield pair
            return

        # Other nodes cannot contain sections, so skip

    def _for_section(self, section_name, callback, ctx=None, scope="all"):
        """
        scope:
          - "included": only before the EXCLUDE marker
          - "excluded": only inside MagicExclusionNode
          - "all":      both
        """
        if scope not in ("all", "included", "excluded"):
            raise ValueError("scope must be 'all', 'included', or 'excluded'")

        out = ctx
        for sec, is_excl in self._iter_section_nodes(self.document, False):
            if section_name and sec.name != section_name:
                continue
            if scope == "included" and is_excl:
                continue
            if scope == "excluded" and not is_excl:
                continue
            out = callback(sec, out)
        return out

    def _get_section(self, section_name):
        section = self._for_section(section_name, identity)
        if section:
            return section
        else:
            raise KeyError("Section [{}] not found".format(section_name))

    def sections(self, scope="all"):
        sections = [x.name for x in self._for_section(None, collect, [], scope=scope)]
        return [x.name for x in self._for_section(None, collect, [], scope=scope)]

    def has_section(self, section_name):
        try:
            return self._get_section(section_name) is not None
        except KeyError:
            return False

    def _save_config_index(self):
        """Top-level index of Klipper's SAVE_CONFIG marker, or None if not present. Nothing
        may be inserted at or after this index"""
        for idx, node in enumerate(self.document.body):
            if isinstance(node, CommentNode):
                text = "".join(e.value for e in node.body if isinstance(e, CommentEntryNode))
                if SAVE_CONFIG_MARKER.match(text.lstrip()):
                    return idx
        return None

    def add_section(self, section_name, comment=None, at_top=False):
        if self.has_section(section_name):
            return

        # Newline after "[section]" header lives inside the section body,
        # matching how parse_section() stores it for parsed files
        section_body = [WhitespaceNode("\n")]
        document_body = []

        if comment:
            document_body.extend([
                CommentNode([CommentEntryNode("# " + comment)]),
                WhitespaceNode("\n"),
            ])

        document_body.append(SectionNode(section_name, section_body))

        if at_top:
            self.document.body[0:0] = document_body
        else:
            boundary_idx = self._save_config_index()

            # if not at_top and include, insert on next line
            inserted = False
            if section_name.startswith("include "):
                last_idx = None
                for idx, node in enumerate(self.document.body):
                    if boundary_idx is not None and idx >= boundary_idx:
                        break
                    if isinstance(node, SectionNode) and node.name.startswith("include "):
                        last_idx = idx

                if last_idx is not None:
                    insert_at = last_idx + 1

                    if insert_at < len(self.document.body):
                        node = self.document.body[insert_at]
                        if isinstance(node, CommentNode):
                            insert_at += 1
                            if (
                                insert_at < len(self.document.body)
                                and isinstance(self.document.body[insert_at], WhitespaceNode)
                                and re.search(r"\r\n|\n|\r", self.document.body[insert_at].value)
                            ):
                                insert_at += 1
                        elif isinstance(node, WhitespaceNode) and re.search(r"\r\n|\n|\r", node.value):
                            insert_at += 1

                    if boundary_idx is not None and insert_at > boundary_idx:
                        insert_at = boundary_idx

                    self.document.body[insert_at:insert_at] = document_body + [WhitespaceNode("\n")]
                    inserted = True

            # append to end if not inserted - but never at or after the SAVE_CONFIG marker
            if not inserted:
                if boundary_idx is not None:
                    self.document.body[boundary_idx:boundary_idx] = document_body + [WhitespaceNode("\n")]
                else:
                    self.document.body.append(WhitespaceNode("\n"))
                    self.document.body.extend(document_body)

    def remove_section(self, section_name):
        self.parser.filter_tree(
            self.document,
            lambda n: isinstance(n, SectionNode) and n.name == section_name,
        )

    def rename_section(self, section_name, new_section_name):
        self._for_section(section_name, rename, new_section_name)

    def _for_option(self, section_name, option_name, callback, ctx=None):
        def for_option(node, ctx, _):
            if isinstance(node, OptionNode) and (not option_name or node.name == option_name):
                ctx = callback(node, ctx)
            return (isinstance(node, SectionNode), ctx)

        section = self._get_section(section_name)
        return section.walk(for_option, ctx)

    def _options(self, section_name):
        return self._for_option(section_name, None, collect, [])

    def _get_option(self, section_name, option_name):
        option = self._for_option(section_name, option_name, identity)
        if option:
            return option
        else:
            raise KeyError("Option '{}' not found".format(option_name))

    def options(self, section_name):
        return [x.name for x in self._options(section_name)]

    def has_option(self, section_name, option_name):
        try:
            return self._for_option(section_name, option_name, identity) is not None
        except KeyError:
            return False

    def copy_option(self, src_config, section_name, option_name):
        option = src_config._get_option(section_name, option_name)
        section = self._get_section(section_name)

        cloned = OptionNode(option.name, copy.deepcopy(option.body), option.assign_op, option.trailing_ws)
        # Pull document-level tail (comments/whitespace after this section) back into the section (your existing behavior)

        doc_body = self.document.body
        try:
            sec_doc_idx = doc_body.index(section)
        except ValueError:
            sec_doc_idx = -1

        if sec_doc_idx != -1:
            j = sec_doc_idx + 1
            while j < len(doc_body) and isinstance(doc_body[j], (CommentNode, WhitespaceNode, HiddenOptionCommentNode)):
                j += 1
            if j > sec_doc_idx + 1:
                section.body.extend(doc_body[sec_doc_idx + 1 : j])
                del doc_body[sec_doc_idx + 1 : j]

        # Decide insertion point: after marker if present, else end
        insert_at = len(section.body)
        marker_idx = None
        for idx, node in enumerate(section.body):
            if isinstance(node, HiddenOptionCommentNode):
                marker_idx = idx

        if marker_idx is not None:
            insert_at = marker_idx + 1
        else:
            insert_at = len(section.body)

        # Ensure we don't tack onto previous line: add newline BEFORE cloned if needed, else AFTER
        nodes_to_insert = []
        if insert_at > 0 and not isinstance(section.body[insert_at - 1], WhitespaceNode):
            nodes_to_insert.append(WhitespaceNode("\n"))
            nodes_to_insert.append(cloned)
        else:
            nodes_to_insert.append(cloned)
            nodes_to_insert.append(WhitespaceNode("\n"))

        section.body[insert_at:insert_at] = nodes_to_insert

    def remove_option(self, section_name, option_name):
        try:
            section = self._get_section(section_name)
            for i, item in enumerate(section.body):
                if isinstance(item, OptionNode) and item.name == option_name:
                    section.body.pop(i)
        except KeyError:
            return

    def rename_option(self, section_name, option_name, new_option_name):
        self._for_option(section_name, option_name, rename, new_option_name)

    def get(self, section_name, option_name, default=None, with_comments=False):
        def serialize(node, buf, _):
            if not with_comments and isinstance(node, CommentNode):
                return False, buf
            return True, buf + node.serialize()

        try:
            option = self._get_option(section_name, option_name)
            if len(option.body) == 0:
                return default
            value = ""
            for value_line in option.body:
                value = value_line.walk(serialize, value)
            return value.strip()
        except KeyError:
            return default

    def getint(self, section_name, option_name, default=None):
        value = self.get(section_name, option_name)
        if value:
            return int(value.strip())
        return default

    def getfloat(self, section_name, option_name, default=None):
        value = self.get(section_name, option_name)
        if value:
            return float(value.strip())
        return default

    def getboolean(self, section_name, option_name, default=None):
        value = self.get(section_name, option_name)
        if value:
            return value.strip().lower() in ["1", "true", "yes", "on"]
        return default

    @staticmethod
    def _find_value_node(option):
        """
        Locate where an option's value text actually starts: the first ValueEntryNode holding
        something other than whitespace. Returns (line index, node), or (0, None) when the
        option carries no value text at all.

        Everything skipped on the way is layout that has to survive a set() - the "\\n" of a
        value that begins on the following line, a blank line, a commented out first entry.
        """
        for i, value_line in enumerate(option.body):
            for node in value_line.body:
                if isinstance(node, ValueEntryNode) and node.value.strip():
                    return i, node
        return 0, None

    def set(self, section_name, option_name, value):
        if value is None:
            logging.warning("{} in section [{}] has no value".format(option_name, section_name))
            value = ""
        value = value.strip()

#        # Neatly indent multi-line values (not required and breaks multi-line drying_data: {...})
#        idx = value.find("\n")
#        if idx != -1:
#            value = value[:idx] + re.sub(r"^(?=\S)", r"    ", value[idx:], flags=re.MULTILINE)

        # Overwrite where the value actually is, which is not always the first ValueEntryNode.
        # A value that starts on the line after the key leaves layout-only nodes in front of
        # it - a bare "\n", a blank line, a commented out first line - and writing over one
        # of those loses the line break ("a: \n    b" came back as "a: b") or, worse, joins
        # the value to a comment ("a: x# c", which configparser reads as the literal "x# c"
        # because an inline comment only counts when whitespace precedes it)
        if self.has_option(section_name, option_name):
            option = self._get_option(section_name, option_name)
            if option.body:
                target_line, target_node = self._find_value_node(option)

                if target_node is None:
                    # Nothing but layout, e.g. an option with no value at all. Put the value
                    # on the key line, ahead of any comment that is sitting there
                    vln = option.body[0]
                    if isinstance(vln.body[0], CommentNode):
                        vln.body.insert(0, ValueEntryNode(value))
                    else:
                        vln.body.append(ValueEntryNode(value))
                else:
                    # Keep the node's own indentation: it is the layout of the line the value
                    # lives on, not part of the value (which arrives here already stripped)
                    indent = target_node.value[: len(target_node.value) - len(target_node.value.lstrip(" \t"))]
                    target_node.value = indent + value

                    # Remove what is left of a multi-lined value, the new one replaces all of
                    # it. E.g.
                    #   [mmu_led_effect mmu_red_strobe]
                    #   layers:       strobe    1 1.5 add (1,1,1)
                    #                 breathing 2 0   difference (0.95,0,0) # animate
                    #                 static    0 0   top (1,0,0)
                    # Only lines after the one just written are candidates, so the layout in
                    # front of the value survives. A line whose ValueEntryNode is whitespace is
                    # retained because it is probably just carrying a comment. E.g.
                    # print_start_detection: 1   # ADVANCED: xxx
                    #                            # ADVANCED: yyy
                    # Side effects:
                    #  - comments on value lines after the value will be removed
                    #  - trailing whitespace on value will be removed (good thing)
                    for i in range(len(option.body) - 1, target_line, -1):
                        first = option.body[i].body[0]
                        if isinstance(first, ValueEntryNode) and first.value.strip() != '':
                            option.body.pop(i)

            else:
                body = self.parser.parse_value(Tokenizer(value, CONFIG_SPEC))
                option.body = body

        else:
            body = self.parser.parse_value(Tokenizer(" " + value, CONFIG_SPEC))
            section = self._get_section(section_name)
            section.body.append(OptionNode(option_name, body, self.parser.default_assign_op))
            section.body.append(WhitespaceNode("\n"))
            option = self._get_option(section_name, option_name)
            option.body = body

    def items(self, section_name):
        section = self._get_section(section_name)
        return [(item.name, item.value()) for item in section.body if isinstance(item, OptionNode)]

    def placeholders(self):
        def collect_placeholders(node, ctx, _):
            if isinstance(node, PlaceholderNode):
                ctx.append(node.value)
            return True, ctx

        return self.document.walk(collect_placeholders, [])


# Simple built-in command line round-trip test for the config parser. Use
# "--check" option to perform byte-by-byte comparison
# "--print" option to pretty print node tree
#
# Usage:
#   python parser.py path/to/printer.cfg <in.cfg>
#   python parser.py path/to/printer.cfg --out <path/to/out.cfg> <in.cfg>
#   python parser.py path/to/printer.cfg --check <in.cfg>
#
if __name__ == "__main__":
    import argparse
    import difflib
    import sys
    from pathlib import Path

    def _decode_with_fallback(data, forced_encoding):
        """
        Return (text, used_encoding). Prefers utf-8/utf-8-sig, falls back to latin-1.
        Preserves UTF-8 BOM by switching to 'utf-8-sig' when present.
        """
        if forced_encoding:
            return data.decode(forced_encoding), forced_encoding

        # Detect UTF-8 BOM
        if data.startswith(b"\xef\xbb\xbf"):
            return data.decode("utf-8-sig"), "utf-8-sig"

        # Try UTF-8, then latin-1
        try:
            return data.decode("utf-8"), "utf-8"
        except UnicodeDecodeError:
            return data.decode("latin-1"), "latin-1"

    def _encode_with_bom_awareness(text, used_encoding):
        if used_encoding == "utf-8-sig":
            # Prepend BOM when encoding (utf-8-sig handles it automatically)
            return text.encode("utf-8-sig")
        return text.encode(used_encoding)

    def _make_parser():
        ap = argparse.ArgumentParser(description="Parse a Klipper-style config and write it back unchanged.")
        ap.add_argument("cfg", type=Path, help="Input config file")
        ap.add_argument(
            "--out",
            type=Path,
            help="Path to write round-tripped output (default: <cfg>.roundtrip)",
        )
        ap.add_argument(
            "--check",
            action="store_true",
            help="Exit 0 if input == output bytes, else 1 and print unified diff.",
        )
        ap.add_argument(
            "--encoding",
            help="Force encoding for read/write (default: auto-detect utf-8/utf-8-sig, fallback latin-1)",
        )
        ap.add_argument(
            "--print",
            action="store_true",
            help="Dump a pretty print of node tree for debugging",
        )
        ap.add_argument(
            "--no-marker",
            action="store_true",
            help="Don't add '# HAPPY HARE PARSE ERROR' marker comments (keeps round trip byte-exact)",
        )
        ap.add_argument(
            "--strict",
            action="store_true",
            help="Abort on the first syntax error instead of recovering from it",
        )
        return ap

    def _main():
        args = _make_parser().parse_args()

        # Read original bytes (no newline normalization)
        try:
            original_bytes = args.cfg.read_bytes()
        except Exception as e:
            sys.stderr.write("[ERROR] Failed to read '{}': {}\n".format(args.cfg, e))
            sys.exit(2)

        # Decode with basic BOM/encoding handling
        try:
            original_text, used_encoding = _decode_with_fallback(original_bytes, forced_encoding=args.encoding)
        except Exception as e:
            sys.stderr.write("[ERROR] Decoding failed: {}\n".format(e))
            sys.exit(2)

        # Parse > serialize
        try:
            parser = Parser(recover=not args.strict, error_marker=not args.no_marker)
            builder = ConfigBuilder(parser=parser)
            builder.read_buf(original_text)
            roundtripped_text = builder.write()
        except Exception as e:
            sys.stderr.write("[ERROR] Parsing/serialization failed: {}\n".format(e))
            sys.exit(2)

        for node in builder.parse_errors():
            sys.stderr.write("[RECOVERED] line {}: {}\n".format(node.line, node.reason))

        # Encode output bytes (preserve BOM if used)
        try:
            out_bytes = _encode_with_bom_awareness(roundtripped_text, used_encoding)
        except Exception as e:
            sys.stderr.write("[ERROR] Encoding failed: {}\n".format(e))
            sys.exit(2)

        out_path = args.out or args.cfg.with_suffix(args.cfg.suffix + ".roundtrip")

        # Write exact bytes (no newline normalization)
        try:
            out_path.write_bytes(out_bytes)
        except Exception as e:
            sys.stderr.write("[ERROR] Failed writing '{}': {}\n".format(out_path, e))
            sys.exit(2)

        # Pretty print node structure for debugging
        if getattr(args, "print"):
            builder.pretty_print_document()

        if args.check:
            if original_bytes == out_bytes:
                print("OK: Round-trip is byte-for-byte identical.")
                sys.exit(0)
            else:
                print("MISMATCH: Round-trip differs. Unified diff:\n")
                # Decode both for human-friendly diff display
                # Use the same encoding we used to write (minus BOM for display)
                diff_from_enc = "utf-8" if used_encoding == "utf-8-sig" else used_encoding
                try:
                    lhs = original_bytes.decode(diff_from_enc, errors="replace")
                except Exception:
                    lhs = original_bytes.decode("latin-1", errors="replace")
                try:
                    rhs = out_bytes.decode(diff_from_enc, errors="replace")
                except Exception:
                    rhs = out_bytes.decode("latin-1", errors="replace")

                diff = difflib.unified_diff(
                    lhs.splitlines(keepends=True),
                    rhs.splitlines(keepends=True),
                    fromfile=str(args.cfg),
                    tofile=str(out_path),
                    n=3,
                )
                sys.stdout.writelines(diff)
                sys.exit(1)
        else:
            print("Wrote round-tripped file to: {}".format(out_path))

    _main()
